# Workflow to build and push a Docker image to Docker Hub
name: Build caddy-geoblock-crowdsec

on:
  workflow_dispatch: # allows manual trigger
  schedule:
    - cron: '0 0 1 * *' # runs at 00:00 on the first day of every month
  push:
    branches: main
    paths:
      - caddy-geoblock-crowdsec/Dockerfile

env:
  DOCKER_BUILDKIT: 1
  DOCKER_NAME: caddy-geoblock-crowdsec
  DOCKER_DESCRIPTION: "Caddy Docker hardened build with Cloudflare DNS, Dynamic DNS, CrowdSec Bouncer, and GeoBlock modules"

jobs:
  metadata:
    name: Get image and repository details
    runs-on: ubuntu-latest

    outputs:
      labels: ${{ steps.metadata.outputs.labels }}
      tags: ${{ steps.metadata.outputs.tags }}
      platforms: linux/amd64,linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate image metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: |
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.DOCKER_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=
          labels: |
            org.opencontainers.image.title=${{ env.DOCKER_NAME }}
            org.opencontainers.image.description=${{ env.DOCKER_DESCRIPTION }}

  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    needs: metadata

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hardened Images registry
        uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ secrets.DHI_USERNAME }}
          password: ${{ secrets.DHI_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish container image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          file: ./${{ env.DOCKER_NAME }}/Dockerfile
          push: true
          provenance: false
          tags: ${{ needs.metadata.outputs.tags }}
          labels: ${{ needs.metadata.outputs.labels }}
          platforms: ${{ needs.metadata.outputs.platforms }}
